In [28]:
import numpy as np

In [29]:
x = np.array([2,4,5])
y = np.array([4,2,5])

In [30]:
y + x

array([ 6,  6, 10])

In [31]:
y - x

array([ 2, -2,  0])

In [32]:
y / x

array([2. , 0.5, 1. ])

In [33]:
# dot product
y = np.array([2,4,5,6])
x = np.array([3,4,5,2])

np.dot(y, x) #the result is scalar 


59

In [34]:
y = np.array([2,3,4])
x = np.array([8,2,1])
y * x #Hadamard product approach, the result is vector, it is the main difference with the previous method - the dot product

array([16,  6,  4])

MATRIX MULTIPLICATION

In [35]:
mat_a = [[2,4,5],
            [1,6,2]]
mat_b = [[1,6],
            [3,1],
            [1,2]]

In [36]:
def matrix_mult(matrix_a, matrix_b):
    # First thing we need to do is check for the shapes - the length of matrix A should be the same as the width (number of rows) of matrix B and the width (number of rows) of matrix B should be the same as length of matrix A so the multiplication can be performed.

    if len(matrix_a[0]) != len(matrix_b): # we check the length of matrix A first element [0] and a number of elements in B because each element is a row.
        raise ValueError("Incompatible matrix shape")
    result = []
    
    for row in range(len(matrix_a)):
        new_row = []
        for col in range(len(matrix_b[0])):
            dot_product = sum(matrix_a[row][k] * matrix_b[k][col] for k in range(len(matrix_b)))
            new_row.append(dot_product)
        result.append(new_row)
    return result

In [37]:
res = matrix_mult(mat_a, mat_b)
res

[[19, 26], [21, 16]]

MATRIX TRANSPOSE
This used when the matrices are not compatible


In [38]:
mat_a

[[2, 4, 5], [1, 6, 2]]

In [39]:
def transpose_mat(m):
    tm = []
    for i in range(len(m[0])):
        new_row = []
        for j in range(len(m)):
            new_row.append(m[j][i])
        tm.append(new_row)
    return tm

In [40]:
transpose_mat(mat_a)

[[2, 1], [4, 6], [5, 2]]

In [41]:
#Sparse_matrces

# architecture and efficiency are a key elements

m_a = [[0,2,0,0,0],
       [0,0,0,0,0],
       [0,1,0,0,0],
       [0,1,0,0,0],
       [0,0,0,0,0]]
m_b = [[0,0,0,0,0],
       [0,0,0,0,0],
       [0,2,0,0,0],
       [0,1,0,2,0],
       [0,0,0,0,0]]

In [52]:
def sparce_mm(matrix_a, matrix_b): #sparce matrix mutiplication funtion
    if len(matrix_a[0]) != len(matrix_b):
        return [[]]
    
    sparce_mat_a = get_useful_values(matrix_a)
    sparce_mat_b = get_useful_values(matrix_b)
    
    matrix_c = [[0] * len(matrix_b[0]) for _ in range(len(matrix_a))] # this line just creates a container, a matrix full of 0 with the shape we want
    #print(matrix_c)
    for i, k in sparce_mat_a.keys():
        for j in range(len(matrix_b[0])):
            if (k,j) in sparce_mat_b.keys():
                matrix_c[i][j] += sparce_mat_a[(i, k)] * sparce_mat_b[(k, j)]
    return matrix_c
        
def get_useful_values(matrix):
    res = {}
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if matrix[i][j] != 0:
                res[(i, j)] = matrix[i][j]
    return res

    #{(0,1):2,}  this is a return form of our dictionary where 0 and 1 is row and column and 2 is a value
        
    

In [50]:
res = sparce_mm(m_a, m_b)
res

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [53]:
a = [[0, 2, 0,],
     [0,0,0]]
b = [[0,1],
     [2,0],
     [1,0]]
res = sparce_mm(a, b)
res

[[0, 0], [0, 0]]


[[4, 0], [0, 0]]